### ISSUE TITLE
Can't install the module

### ISSUE THREAD

**Issue by Symbiot78** [JonasPed/pydanfoss-air#2]
Hi Jonas
I am hoping to get your tool working.
unfortunately I hit a snag at the very beginning.
When trying to install the module I am met with this:
I know nothing of Python and it's probably a * fejl 40 * but I hope you can point it out to me :-)

` sudo python setup.py install --prefix=~

Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
`

**Comment by JonasPed1** [comment]
Usually python packages are installed using pip. So not sure why you are using mentioned command? However I tried above using Python 3.8 and it works without any issues.

**Comment by Symbiot78** [comment]
I have 3.7 on my rpi. 
I used pip instead and ran:

 pip3 install git+https://github.com/JonasPed/pydanfoss-air.git

then:

 python3 -m pydanfossair --host 192.168.1.194

which gave me:

ReadCommand.exhaustTemperature: 9.1
ReadCommand.supplyTemperature: 20.1
ReadCommand.extractTemperature: 21.85
ReadCommand.outdoorTemperature: 6.89
ReadCommand.humidity: 34.11764705882353
ReadCommand.bypass: False
ReadCommand.filterPercent: 0.0
ReadCommand.boost: False
ReadCommand.supply_fan_speed: 1030
ReadCommand.exhaust_fan_speed: 1094
ReadCommand.fan_step: 20
ReadCommand.away_mode: False
ReadCommand.battery_percent: 24.705882352941178
ReadCommand.automatic_bypass: True
ReadCommand.operation_mode: OperationMode.demand
