### ISSUE TITLE
ReadCommand.fan_step does not work with my AirUnit

### ISSUE THREAD

**Issue by mschlappa** [JonasPed/pydanfoss-air#4]
Hi Jonas,

i am doing my first babysteps with HomeAssistant and i am testing the "Danfoss Air" Integration.
My problem is that the manual_step read command always returns 0.

I noticed that the integration uses your `pydanfoss-air` library and discovered a deviation from another SmartHome platform (OpenHAB).

In your command.py i found

`fan_step = bytes([0x00, 0x04, 0x17, 0x81])`

In [OpenHAB i found](https://github.com/openhab/openhab-addons/blob/6829ff657ab27a35e5ab54913f64b803624e7e11/bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/Commands.java#L38)

`MANUAL_FAN_SPEED_STEP = { 0x15, 0x61 }`

I changed the command.py in `pydanfoss-air` to 

`fan_step = bytes([0x01, 0x04, 0x15, 0x61])`

I tried it with the commandline Client and it works now for my AirUnit.

My questions:

- Are there maybe different implementations of the commands in the Danfoss Air Units?
- How do i get the fix installed in my Home Assistant instance?

Thanks in advance for your answer!

Greetings
Marcus

**Comment by mschlappa** [comment]
Maybe this ticket is related to my issue?

https://github.com/home-assistant/core/issues/101041

**Comment by mschlappa** [comment]
I created some other small  fixes in this PullRequest:

https://github.com/JonasPed/pydanfoss-air/pull/5

**Comment by JonasPed** [comment]
Just created a new release. That package needs to get updated in HA.
